// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/user/delivery/grpc/proto/user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string               `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address              string               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8668573c2d11bbe, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type UserCreateReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateReq) Reset()         { *m = UserCreateReq{} }
func (m *UserCreateReq) String() string { return proto.CompactTextString(m) }
func (*UserCreateReq) ProtoMessage()    {}
func (*UserCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8668573c2d11bbe, []int{1}
}

func (m *UserCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateReq.Unmarshal(m, b)
}
func (m *UserCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateReq.Marshal(b, m, deterministic)
}
func (m *UserCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateReq.Merge(m, src)
}
func (m *UserCreateReq) XXX_Size() int {
	return xxx_messageInfo_UserCreateReq.Size(m)
}
func (m *UserCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateReq proto.InternalMessageInfo

func (m *UserCreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserCreateReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserCreateReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserCreateReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UserUpdateReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateReq) Reset()         { *m = UserUpdateReq{} }
func (m *UserUpdateReq) String() string { return proto.CompactTextString(m) }
func (*UserUpdateReq) ProtoMessage()    {}
func (*UserUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8668573c2d11bbe, []int{2}
}

func (m *UserUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateReq.Unmarshal(m, b)
}
func (m *UserUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateReq.Marshal(b, m, deterministic)
}
func (m *UserUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateReq.Merge(m, src)
}
func (m *UserUpdateReq) XXX_Size() int {
	return xxx_messageInfo_UserUpdateReq.Size(m)
}
func (m *UserUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateReq proto.InternalMessageInfo

func (m *UserUpdateReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserUpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserUpdateReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserUpdateReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserUpdateReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UserIDReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIDReq) Reset()         { *m = UserIDReq{} }
func (m *UserIDReq) String() string { return proto.CompactTextString(m) }
func (*UserIDReq) ProtoMessage()    {}
func (*UserIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8668573c2d11bbe, []int{3}
}

func (m *UserIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIDReq.Unmarshal(m, b)
}
func (m *UserIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIDReq.Marshal(b, m, deterministic)
}
func (m *UserIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIDReq.Merge(m, src)
}
func (m *UserIDReq) XXX_Size() int {
	return xxx_messageInfo_UserIDReq.Size(m)
}
func (m *UserIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserIDReq proto.InternalMessageInfo

func (m *UserIDReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UsersReq struct {
	Page                 string   `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              string   `protobuf:"bytes,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	OrderBy              string   `protobuf:"bytes,3,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	SelectField          string   `protobuf:"bytes,4,opt,name=selectField,proto3" json:"selectField,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAtStart       string   `protobuf:"bytes,8,opt,name=createdAtStart,proto3" json:"createdAtStart,omitempty"`
	CreatedAtEnd         string   `protobuf:"bytes,9,opt,name=createdAtEnd,proto3" json:"createdAtEnd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersReq) Reset()         { *m = UsersReq{} }
func (m *UsersReq) String() string { return proto.CompactTextString(m) }
func (*UsersReq) ProtoMessage()    {}
func (*UsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8668573c2d11bbe, []int{4}
}

func (m *UsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersReq.Unmarshal(m, b)
}
func (m *UsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersReq.Marshal(b, m, deterministic)
}
func (m *UsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersReq.Merge(m, src)
}
func (m *UsersReq) XXX_Size() int {
	return xxx_messageInfo_UsersReq.Size(m)
}
func (m *UsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_UsersReq proto.InternalMessageInfo

func (m *UsersReq) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *UsersReq) GetPerPage() string {
	if m != nil {
		return m.PerPage
	}
	return ""
}

func (m *UsersReq) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *UsersReq) GetSelectField() string {
	if m != nil {
		return m.SelectField
	}
	return ""
}

func (m *UsersReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UsersReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UsersReq) GetCreatedAtStart() string {
	if m != nil {
		return m.CreatedAtStart
	}
	return ""
}

func (m *UsersReq) GetCreatedAtEnd() string {
	if m != nil {
		return m.CreatedAtEnd
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              int64    `protobuf:"varint,3,opt,name=perPage,proto3" json:"perPage,omitempty"`
	TotalPage            int64    `protobuf:"varint,4,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	TotalData            int64    `protobuf:"varint,5,opt,name=totalData,proto3" json:"totalData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8668573c2d11bbe, []int{5}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Users) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Users) GetPerPage() int64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Users) GetTotalPage() int64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *Users) GetTotalData() int64 {
	if m != nil {
		return m.TotalData
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*UserCreateReq)(nil), "proto.UserCreateReq")
	proto.RegisterType((*UserUpdateReq)(nil), "proto.UserUpdateReq")
	proto.RegisterType((*UserIDReq)(nil), "proto.UserIDReq")
	proto.RegisterType((*UsersReq)(nil), "proto.UsersReq")
	proto.RegisterType((*Users)(nil), "proto.Users")
}

func init() {
	proto.RegisterFile("api/v1/user/delivery/grpc/proto/user.proto", fileDescriptor_f8668573c2d11bbe)
}

var fileDescriptor_f8668573c2d11bbe = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0xbf, 0xdd, 0x4c, 0x96, 0x05, 0x59, 0x7b, 0xb0, 0x0a, 0x12, 0x25, 0x12, 0x50,
	0xb1, 0x28, 0x11, 0xe5, 0xc4, 0x71, 0xa1, 0x20, 0x21, 0x71, 0x40, 0x5d, 0xf6, 0x8c, 0xbc, 0xf5,
	0x50, 0x2c, 0xa5, 0x4d, 0x70, 0xdc, 0x4a, 0xbd, 0xf1, 0x10, 0xbc, 0x22, 0x3c, 0x07, 0xb2, 0x9d,
	0x98, 0x84, 0x16, 0x71, 0xdb, 0x53, 0xed, 0xdf, 0x67, 0x7b, 0xe6, 0xfb, 0x32, 0x85, 0x67, 0xac,
	0x16, 0xc5, 0xee, 0x45, 0xb1, 0x6d, 0x50, 0x16, 0x1c, 0x4b, 0xb1, 0x43, 0xb9, 0x2f, 0x56, 0xb2,
	0x5e, 0x16, 0xb5, 0xac, 0x54, 0x65, 0x84, 0xdc, 0x2c, 0x49, 0x64, 0x7e, 0xc6, 0x0f, 0x57, 0x55,
	0xb5, 0x2a, 0xd1, 0xea, 0x37, 0xdb, 0x2f, 0x85, 0x12, 0x6b, 0x6c, 0x14, 0x5b, 0xd7, 0xf6, 0x5c,
	0xf6, 0xcb, 0x83, 0xf0, 0xba, 0x41, 0x49, 0xce, 0xc0, 0x17, 0x9c, 0x7a, 0x13, 0x6f, 0x9a, 0x2c,
	0x7c, 0xc1, 0x09, 0x81, 0x70, 0xc3, 0xd6, 0x48, 0x7d, 0x43, 0xcc, 0x9a, 0x9c, 0x43, 0x54, 0x7f,
	0xad, 0x36, 0x48, 0x03, 0x03, 0xed, 0x46, 0x53, 0x5c, 0x33, 0x51, 0xd2, 0xd0, 0x52, 0xb3, 0x21,
	0x14, 0x46, 0x8c, 0x73, 0x89, 0x4d, 0x43, 0x23, 0xc3, 0xbb, 0x2d, 0x79, 0x05, 0xb0, 0xad, 0x39,
	0x53, 0xc8, 0x3f, 0x33, 0x45, 0xe3, 0x89, 0x37, 0x4d, 0x67, 0xe3, 0xdc, 0x36, 0x9a, 0x77, 0x8d,
	0xe6, 0x9f, 0xba, 0x46, 0x17, 0x49, 0x7b, 0xfa, 0x52, 0xe9, 0xab, 0x4b, 0x89, 0xdd, 0xd5, 0xd1,
	0xff, 0xaf, 0xb6, 0xa7, 0x2f, 0x55, 0x26, 0xe0, 0x8e, 0xf6, 0xf9, 0xc6, 0x80, 0x05, 0x7e, 0x73,
	0x06, 0xbd, 0x63, 0x06, 0xfd, 0xa3, 0x06, 0x83, 0x7f, 0x18, 0x0c, 0x07, 0x06, 0xb3, 0xbd, 0x2d,
	0x75, 0x6d, 0xda, 0xd6, 0xa5, 0x6e, 0x2d, 0xdb, 0xec, 0x3e, 0x24, 0xba, 0xf4, 0xfb, 0xf9, 0x91,
	0xb2, 0xd9, 0x77, 0x1f, 0x4e, 0xb4, 0xda, 0xb4, 0xf6, 0x6b, 0xb6, 0x72, 0xf6, 0xf5, 0x5a, 0xbf,
	0x5b, 0xa3, 0xfc, 0xa8, 0xb1, 0x6d, 0xad, 0xdb, 0x6a, 0xa5, 0x92, 0x1c, 0xe5, 0xeb, 0x7d, 0xdb,
	0x5f, 0xb7, 0x25, 0x13, 0x48, 0x1b, 0x2c, 0x71, 0xa9, 0xde, 0x09, 0x2c, 0x79, 0xdb, 0x67, 0x1f,
	0x39, 0xb7, 0xd1, 0xd0, 0xad, 0xf5, 0x15, 0xf7, 0x7d, 0xb9, 0x0c, 0x46, 0xfd, 0x0c, 0x9e, 0xc0,
	0x99, 0xfb, 0x8c, 0x57, 0x8a, 0x49, 0x45, 0x4f, 0x8c, 0xfc, 0x17, 0x25, 0x19, 0x9c, 0x3a, 0xf2,
	0x76, 0xc3, 0x69, 0x62, 0x4e, 0x0d, 0x58, 0xf6, 0xc3, 0x83, 0xc8, 0x44, 0x40, 0x1e, 0x41, 0xa4,
	0xff, 0x2e, 0x0d, 0xf5, 0x26, 0xc1, 0x34, 0x9d, 0xa5, 0x76, 0x7c, 0x72, 0x2d, 0x2e, 0xac, 0xe2,
	0x22, 0xd2, 0x59, 0x04, 0x87, 0x11, 0x05, 0x06, 0xbb, 0x88, 0x1e, 0x40, 0xa2, 0x2a, 0xc5, 0x4a,
	0xa3, 0x85, 0x46, 0xfb, 0x03, 0x9c, 0x3a, 0x67, 0x8a, 0x99, 0x24, 0x3a, 0x55, 0x83, 0xd9, 0x4f,
	0x0f, 0x52, 0x5d, 0xf9, 0x0a, 0xe5, 0x4e, 0x2c, 0x91, 0x5c, 0x40, 0x6c, 0x07, 0x95, 0x9c, 0xf7,
	0xfa, 0x72, 0xb3, 0x3b, 0xee, 0x77, 0x4b, 0x1e, 0x43, 0xf8, 0x41, 0x34, 0x8a, 0xdc, 0xed, 0x41,
	0xfd, 0x89, 0xc7, 0xa7, 0x7d, 0x40, 0x9e, 0x42, 0x3c, 0x47, 0xa5, 0x63, 0xbe, 0xd7, 0xe3, 0x66,
	0x52, 0x86, 0xef, 0x5d, 0x40, 0x6c, 0x47, 0x77, 0x50, 0xdc, 0x4d, 0xf3, 0xf0, 0xf0, 0x73, 0xfd,
	0x6a, 0x89, 0x0a, 0x8f, 0xbc, 0x7a, 0x40, 0x6e, 0x62, 0x03, 0x5e, 0xfe, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0xfe, 0xde, 0x86, 0xa4, 0xca, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*User, error)
	List(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*Users, error)
	Detail(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*User, error)
	Update(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*User, error)
	Delete(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*UserIDReq, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) List(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/proto.UserService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Detail(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.UserService/Detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*UserIDReq, error) {
	out := new(UserIDReq)
	err := c.cc.Invoke(ctx, "/proto.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *UserCreateReq) (*User, error)
	List(context.Context, *UsersReq) (*Users, error)
	Detail(context.Context, *UserIDReq) (*User, error)
	Update(context.Context, *UserUpdateReq) (*User, error)
	Delete(context.Context, *UserIDReq) (*UserIDReq, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *UserCreateReq) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserServiceServer) List(ctx context.Context, req *UsersReq) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedUserServiceServer) Detail(ctx context.Context, req *UserIDReq) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detail not implemented")
}
func (*UnimplementedUserServiceServer) Update(ctx context.Context, req *UserUpdateReq) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserServiceServer) Delete(ctx context.Context, req *UserIDReq) (*UserIDReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*UserCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).List(ctx, req.(*UsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Detail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Detail(ctx, req.(*UserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UserUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*UserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserService_List_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _UserService_Detail_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/user/delivery/grpc/proto/user.proto",
}
